### ISSUE TITLE
Site Background

### ISSUE THREAD

**Issue by Turtle84375** [Turtle84375/turtle84375.tk#26]
To Do:
Add a nice site background, at least to the homepage, a gradient will do nicely.

Blue?

**Comment by GabrielF11** [comment]
![Screen Shot 2021-10-01 at 5 25 19 PM](https://user-images.githubusercontent.com/88408682/135697812-a5ba73f9-18e2-4a8c-91ed-ae9412139a66.png)
Something like this? Or have the header be that and the rest be something else?

**Comment by Turtle84375** [comment]
Yeah, I'm trying to get the header to be that, and have white space below where I can put other things.

**Comment by GabrielF11** [comment]
Ok.

**Comment by Turtle84375** [comment]
@GabrielF11 Ended up using this one, thanks!
