### ISSUE TITLE
Dev view

### ISSUE THREAD

**Issue by WatchAndGame** [Turtle84375/turtle84375.tk#28]
Basically a button that shows you all of the elements in a page (like `<p>hi</p>` instead of hi). It would be pretty cool.

**Comment by Turtle84375** [comment]
@WatchAndGame I'll look into it!

**Comment by Turtle84375** [comment]
Note to self: https://stackoverflow.com/questions/29094827/how-to-add-an-icon-to-a-button-at-the-bottom-right-corner

**Comment by Turtle84375** [comment]
Button UI complete.

**Comment by Turtle84375** [comment]
Note to self: use LocalStorage for cross-page transfer.

**Comment by Turtle84375** [comment]
@WatchAndGame Basic framework complete!

**Comment by Turtle84375** [comment]
More or less finished, just need to implement on other pages, but I made it flexible so it'll easily implement.

**Comment by Turtle84375** [comment]
Test

**Comment by Turtle84375** [comment]
Test

**Comment by Turtle84375** [comment]
Test

**Comment by Turtle84375** [comment]
Test

**Comment by Turtle84375** [comment]
Test

**Comment by Turtle84375** [comment]
Test

**Comment by Turtle84375** [comment]
Test

**Comment by Turtle84375** [comment]
Test

**Comment by Turtle84375** [comment]
Test

**Comment by Turtle84375** [comment]
Test

**Comment by Turtle84375** [comment]
Test

**Comment by Turtle84375** [comment]
Test
