### ISSUE TITLE
Implement Socket.io Chat

### ISSUE THREAD

**Issue by Turtle84375** [Turtle84375/turtle84375.tk#35]
Will require login.

Need to fetch framework.

**Comment by Quantum-Codes** [comment]
Done??

**Comment by Turtle84375** [comment]
> Done??

Not quite, I have the Socket.io chat set up but it's not linked to chat.turtle84375.tk yet. I'll probably do this tonight, I've been neglecting this repository to be honest since I have a few other projects like TurtleHosting and TrackTask to work on.

**Comment by Turtle84375** [comment]
The current chat.turtle84375.tk is a PHP webserver chat, not as reliable as Socket.io.

**Comment by Quantum-Codes** [comment]
> The current chat.turtle84375.tk is a PHP webserver chat, not as reliable as Socket.io.

Ohh ok

**Comment by Turtle84375** [comment]
Resolved with new https://chat.turtle84375.tk
