### ISSUE TITLE
Second URL?

### ISSUE THREAD

**Issue by AwesomePotato23** [Turtle84375/turtle84375.tk#39]
So I have an idea. You know how your site uses a .tk domain? My school blocks those due to proxy stuffs and I can't bypass Securly anymore. So I'm wondering if it is possible to host it on something like GitHub Pages at the same time as well. Like you could have the .tk domain for people who can see it and GitHub pages as a backup. I think it'd be pretty cool :)

Edit: I realised this is ran with GitHub Pages but used a custom URL--
Case closed lol

**Comment by Turtle84375** [comment]
xD yeah, I made the custom domain because it looks more professional and my own school blocks all .github.io domains, but it should be accessible at both https://turtle84375.tk and https://turtle84375.github.io/turtle84375-tk .
