### ISSUE TITLE
Connect turtle84375.tk to Cloudflare

### ISSUE THREAD

**Issue by Turtle84375** [Turtle84375/turtle84375.tk#5]
Having issues doing this, keep getting this error:
![image](https://user-images.githubusercontent.com/91347263/134984638-fe9b936d-9800-448e-a21c-a1021cf9d03f.png)

@Gabrielf11, how did you add your domain to Cloudflare??

**Comment by Turtle84375** [comment]
Hm. I'll try again later.

**Comment by GabrielF11** [comment]
Apparently the Freenom WHOIS is down, causing the issue. Hopefully they fix it soon. Also, not sure why it didn't affect mine.

https://stackoverflow.com/questions/69028830/failed-to-lookup-registrar-and-hosting-information-freenom

**Comment by Turtle84375** [comment]
Yay, finally got it to work! Closing as resolved.
