### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Turtle84375** [Turtle84375/turtle84375.tk#6]
Anyone have any good CSS templates they would recommend?

**Comment by GabrielF11** [comment]
A simple and good one would be [Water.css](https://watercss.kognise.dev/). I was playing around with how it would look on your website, and I got this
![Screen Shot 2021-09-29 at 11 35 49 AM](https://user-images.githubusercontent.com/88408682/135328528-43a1e418-c79c-47bd-aabe-548681b7acfe.png)
I'm not sure what style you're going for, but it's a good starting option. I forked this respiratory and made a few simple changes to see what it would look like.

**Comment by Turtle84375** [comment]
Cool, could you make your changes into a pull request so I can test the branch on the live site?

**Comment by GabrielF11** [comment]
Sure!

**Comment by Turtle84375** [comment]
@GabrielF11 I like Water.css on the login page, but not really anywhere else. Thanks for the suggestion, though, I'll still use it in the site :)

**Comment by Turtle84375** [comment]
To Do: Implement https://www.w3schools.com/w3css/tryit.asp?filename=tryw3css_templates_startup

**Comment by Turtle84375** [comment]
Will continue to build framework around this CSS :)
